[package]
name = "stark-storage"
version.workspace = true
edition.workspace = true

[dependencies]
stark-domain = { path = "../domain" }
rusqlite = { version = "0.37", features = ["bundled"] }
thiserror = "2"
time = { version = "0.3", features = ["formatting", "macros", "local-offset"] }
serde = { version = "1", features = ["derive"] }
stark-planning = { path = "../planning" }
stark-ai = { path = "../ai" }